branches:
  only:
  - master

language: cpp

compiler:
  - g++

os:
  - linux

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq g++-4.8 g++-4.8-multilib linux-libc-dev linux-libc-dev:i386

before_script:
  - cd tests

script:
  - mkdir build_x64
  - cd build_x64
  - CXX=g++-4.8 CXXFLAGS=-m64 cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --verbose
  - ctest --output-on-failure
  - cd ..
  - mkdir build_x32
  - cd build_x32
  - CXX=g++-4.8 CXXFLAGS=-m32 cmake .. -DCMAKE_BUILD_TYPE=Release
  - cmake --build . --verbose
  - ctest --output-on-failure
