language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

before_script:
  - cd tests

script:
  - echo "script begin"
  - CONFIGURATION=debug make
  - ./tests
  - make clean
  - echo "script end"
  - uname -a
