language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

before_script:
  - cd tests

script:
  - echo "script begin"
  - COMPILER=g++-4.8 CONFIGURATION=debug make
  - ./tests
  - make clean
  - echo "script end"
  - uname -a
  - gcc -v
  - clang -v

addons:
  apt:
    packages:
    - gcc-4.8
    - g++-4.8
    - clang
